index:
  path: /
  controller: App\Actions\GeneralAction::index
  requirements:
    page: '.+'

react-routing:
  path: /{routing}
  controller: App\Actions\GeneralAction::reactRouting
  requirements:
    page: '.+'

react-routing2:
  path: /{routing1}/{routing2}
  controller: App\Actions\GeneralAction::reactRouting
  requirements:
    page: '.+'

user-register:
  path: /api/rest/v1/auth/register
  controller: App\Actions\Users\UserRegisterAction
  methods: POST

api_login_check:
  path: /api/rest/v1/auth/login_check

token_refresh:
  path: /api/rest/v1/token/refresh
  controller: App\Actions\SecurityAction::refreshToken

todo-index:
  path: /api/rest/v1/{username}/todos
  controller: App\Actions\Todos\TodoIndexAction
  methods: GET
